/* EDIT KONTEN DI FILE INI SAJA. Semua data di bawah adalah contoh.
   Ganti file foto/musik di assets, lalu ubah path di sini.
   Tanggal ISO wajib memuat zona waktu: +07:00 (WIB), +08:00 (WITA), +09:00 (WIT).
   Nama tamu: bagikan index.html?to=Nama%20Tamu. Parameter ditampilkan sebagai teks aman. */
window.INVITATION_DATA = {
  // Judul bagian & label publik juga terpusat di sini.
  ui: {
    coverBlessing: "DENGAN RAHMAT ALLAH SWT",
    guestSalutation: "Kepada Yth. Bapak/Ibu/Saudara/i",
    guestPlace: "Di tempat",
    open: "Buka Undangan",
    opened: "Undangan terbuka",
    openingEyebrow: "BISMILLAHIRRAHMANIRRAHIM",
    coupleEyebrow: "YANG BERBAHAGIA",
    coupleHeading: "Sepasang hati",
    eventsEyebrow: "HARI ISTIMEWA KAMI",
    eventsHeading: "Janji & perayaan",
    countdownEyebrow: "SETIAP DETIK MENUJU",
    countdownHeading: "Hari bahagia",
    countdownUnits: ["Hari", "Jam", "Menit", "Detik"],
    giftsEyebrow: "TANDA KASIH",
    giftsHeading: "Amplop digital",
    galleryEyebrow: "Galeri",
    galleryHeading: "Foto",
    footerEyebrow: "KAMI YANG BERBAHAGIA",
    closeCalendar: "Tutup pilihan kalender",
    maps: "Buka Google Maps",
    calendar: "Simpan ke Kalender",
    googleCalendar: "Google Calendar",
    appleCalendar: "Apple / Outlook (.ics)",
    copySuccess: "Nomor berhasil disalin",
    copyFailed: "Silakan salin nomor secara manual",
    musicPlay: "Putar musik",
    musicMute: "Bisukan musik",
    musicError: "Musik belum dapat diputar. Ketuk tombol musik untuk mencoba.",
  },
  // Background tiap bagian dapat diganti di sini saja.
  backgrounds: {
    cover: "assets/decor/background-cover.webp",
    opening: "assets/decor/background-floral.webp",
    couple: "assets/decor/background-floral.webp",
    events: "assets/decor/background-maroon.webp",
    countdown: "assets/decor/background-cover.webp",
    gifts: "assets/decor/background-gallery.webp",
    gallery: "assets/decor/background-gallery.webp",
    closing: "assets/decor/background-cover.webp",
  },
  title: "Undangan Pernikahan · Iqbal & Adinda",
  coverLabel: "THE WEDDING OF",
  coupleNames: "Iqbal & Adinda",
  guestFallback: "Bapak/Ibu/Saudara/i",
  timezone: "Asia/Jakarta",
  timeLabel: "WIB",
  coverPhoto: "assets/photos/couple.jpeg",
  greeting: "Assalamu’alaikum Warahmatullahi Wabarakatuh",
  intro:
    "Dengan memohon rahmat dan ridha Allah SWT, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada pernikahan kami.",
  quote:
    "Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
  quoteSource: "QS. Ar-Rum: 21",
  profiles: [
    {
      nickname: "Iqbal",
      name: "Iqbal Pangestu",
      family: "Putra dari Bapak Jamalis S.Pd., SD & Ibu Almuni Derita",
      photo: "assets/photos/iqbal.png",
      alt: "Foto Iqbal",
    },
    {
      nickname: "Adinda",
      name: "Adinda Putri",
      family: "Putri dari Bapak Drs. Busnar & Ibu Darwanis",
      photo: "assets/photos/adinda.png",
      alt: "Foto Adinda",
    },
  ],
  eventIntro: "Insya Allah, rangkaian acara akan diselenggarakan pada:",
  events: [
    {
      title: "Akad Nikah",
      start: "2026-11-21T09:00:00+07:00",
      end: "2026-12-20T10:30:00+07:00",
      venue: "Kediaman Mempelai Wanita",
      address: "Jl. Jeruk II No. 85, RT 004/RW 011, Kec. Kuranji, Kota Padang",
      mapUrl: "https://maps.app.goo.gl/75b4V4ZAoRYNM5vD7",
      calendar: {
        title: "Akad Nikah Iqbal & Adinda",
        description: "Mohon doa restu untuk pernikahan kami.",
        location: "Jl. Jeruk II No. 85, RT 004/RW 011, Kec. Kuranji, Kota Padang",
      },
    },
    {
      title: "Resepsi",
      start: "2026-11-21T13:00:00+07:00",
      end: "2026-11-21T22:00:00+07:00",
      venue: "Kediaman Mempelai Wanita",
      address: "Jl. Jeruk II No. 85, RT 004/RW 011, Kec. Kuranji, Kota Padang",
      mapUrl: "https://maps.app.goo.gl/75b4V4ZAoRYNM5vD7",
      calendar: {
        title: "Resepsi Iqbal & Adinda",
        description: "Kami menantikan kehadiran Anda.",
        location: "Jl. Jeruk II No. 85, RT 004/RW 011, Kec. Kuranji, Kota Padang",
      },
    },
  ],
  countdownTarget: "2026-11-21T09:00:00+07:00",
  countdownCaption: "Semoga langkah kita dipertemukan dalam kebahagiaan.",
  countdownFinished: "Hari bahagia telah tiba. Terima kasih atas doa restu Anda.",
  giftMessage:
    "Doa restu Anda adalah hadiah terindah bagi kami. Apabila berkenan memberikan tanda kasih, Anda dapat mengirimkannya melalui:",
  accounts: [
    { provider: "BRI", number: "056001066277500", holder: "Iqbal Pangestu", label: "Salin No. Rekening" },
    { provider: "BCA", number: "3121053720", holder: "Adinda Putri", label: "Salin No. Rekening" },
  ],
  // Grid galeri 3 kolom: tambah/hapus foto sesuai kebutuhan.
  gallery: [
    { src: "assets/photos/gallery-1.jpeg", alt: "Momen bersama 1" },
    { src: "assets/photos/gallery-2.jpeg", alt: "Momen bersama 2" },
    { src: "assets/photos/gallery-3.jpeg", alt: "Momen bersama 3" },
    { src: "assets/photos/gallery-4.jpeg", alt: "Momen bersama 4" },
    { src: "assets/photos/gallery-5.jpeg", alt: "Momen bersama 5" },
    { src: "assets/photos/gallery-6.jpeg", alt: "Momen bersama 6" },
    { src: "assets/photos/gallery-7.jpeg", alt: "Momen bersama 7" },
    { src: "assets/photos/gallery-8.jpeg", alt: "Momen bersama 8" },
    { src: "assets/photos/gallery-9.jpeg", alt: "Momen bersama 9" },
    { src: "assets/photos/gallery-10.jpeg", alt: "Momen bersama 10" },
    { src: "assets/photos/gallery-11.jpeg", alt: "Momen bersama 11" },
    { src: "assets/photos/gallery-12.jpeg", alt: "Momen bersama 12" },
  ],
  music: { src: "assets/music/melody.wav", enabled: true, volume: 0.3 },
  closing:
    "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta memberikan doa restu. Terima kasih atas kasih dan doa yang menyertai perjalanan kami.",
  closingGreeting: "Wassalamu’alaikum Warahmatullahi Wabarakatuh",
  footerCredit: "Dibuat dengan kasih · Iqbal & Adinda",
};
